version: "2"
services:
  game:
    build: "game"
    command: "--latency-ms 250 --start-server default"
    volumes:
      - "saves:/opt/factorio/saves"
      - "mods:/opt/factorio/mods"
    ports:
      - "34197:34197/tcp"
      - "34197:34197/udp"
    environment:
      SAVE_FILE_URL:
      MODS_FILE_URL:
volumes:
  saves:
    driver: local
  mods:
    driver: local
