version: "2"
services:
  factorio:
    build: "game"
    command: "--latency-ms 250 --start-server default"
    volumes:
      - "saves:/opt/factorio/saves"
      - "mods:/opt/factorio/mods"
    ports:
      - "34197:34197/tcp"
      - "34197:34197/udp"

volumes:
  saves:
  mods:
