version: "2"
services:
  factorio:
    build: "."
    command: "--latency-ms 250 --start-server default"
    volumes:
      - "${PWD}/saves:/opt/factorio/saves"
    ports:
      - "34197:34197/tcp"
      - "34197:34197/udp"

volumes:
  s3:
    driver: s3
    driver_opts:
      region: us-east-1
      bucket: factorio.pickaxe.me
