version: "2"
services:
  factorio:
    build: "game"
    command: "--latency-ms 250 --start-server default"
    volumes:
      - "${PWD}/saves:/opt/factorio/saves"
    ports:
      - "34197:34197/tcp"
      - "34197:34197/udp"
